# Generated by Django 4.1.5 on 2023-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('is_published', models.CharField(max_length=5)),
            ],
        ),
    ]
