# Generated by Django 4.1.5 on 2023-01-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_admodel_ad_rename_categorymodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
    ]
